name: first workflow
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: hello 
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: more and more
        env:
          JOB_CONTEXT: ${{toJson(job)}}

        run: | 
          echo "Job Cotnext: $JOB_CONTEXT"
          echo "done!"
