name: first workflow
on: [push,pull_request]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: hello 
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: more and more
        env:
          JOB_CONTEXT: ${{toJson(job)}}

        run: | 
          echo "Job Cotnext: $JOB_CONTEXT"
          echo "done!"

      - name: install dependencies        
        working-directory: ./lessons/03-Continious_Integration/03.1-Executing_tests
        run: composer install --ignore-platform-reqs 

      - name: Run the tests
        working-directory: ./lessons/03-Continious_Integration/03.1-Executing_tests
        run: composer phpunit
        